# Python CircleCI 2.0 configuration file
version: 2
workflows:
  version: 2
  build:
    jobs:
      - build-python-3.6
jobs:
  build-python-3.6: &build-template
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build package
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 setup.py sdist
      - run:
          name: Install dependencies
          command: |
            sudo pip install --upgrade pip
            sudo pip install .[dev]
      - run:
          name: Run pre-commit hooks
          command: |
            pre-commit run --all-files
      - run:
          name: Run tests
          command: |
            python3 setup.py test
  build-python-3.7:
    <<: *build-template
    docker:
      - image: circleci/python:3.7
