# Python CircleCI 2.0 configuration file
version: 2
workflows:
  version: 2
  build:
    jobs:
      - build-python-3.6
      - build-python-3.7
      - build-python-3.8
jobs:
  build-python-3.6: &build-template
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build package
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py sdist
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt ."[dev]"
      - run:
          name: Run pre-commit hooks
          command: |
            pre-commit run --all-files
      - run:
          name: Run tests
          command: |
            coverage run --source=pyesg -m unittest discover --verbose
      - run:
          name: Send coverage report
          command: |
            pip install coveralls
            coveralls
  build-python-3.7:
    <<: *build-template
    docker:
      - image: circleci/python:3.7
  build-python-3.8:
    <<: *build-template
    docker:
      - image: circleci/python:3.8
